### ISSUE TITLE
powerfighter: fails to detect slayer task complete when point boosting

### ISSUE THREAD

**Issue by SRLJustin** [illumineawake/illu-plugins#63]
When 'Stop on Slayer task completion" is selected and you're point boosting the task message isn't the standard one, meaning slayerCompleted is never set to true

![image](https://user-images.githubusercontent.com/1625140/98438276-3f151500-213d-11eb-89f7-59a3799faceb.png)

**Comment by illumineawake** [comment]
Resolved in v3.4.0
What's your disc?

**Comment by SRLJustin** [comment]
thanks, justin#7856
