### ISSUE TITLE
Power Skiller Dense Essence. 

### ISSUE THREAD

**Issue by Gittyhub123** [illumineawake/illu-plugins#71]
Hi. This isn't an issue as such, just a question since the readme is not very detailed. If I want the power skiller to only mine the dense essence for me (IE, switch between the two rocks automatically and stop one the inventory is full), can I just leave everything empty? Object type Dense Essence, make sure the location radius covers both essence rocks, then the rest unticked/empty? 
Many thanks if you answer @illumineawake

**Comment by MeApeSmallBrain** [comment]
Have you tried doing it that way?

**Comment by Gittyhub123** [comment]
> Have you tried doing it that way?

Not yet. For some reason I don't like trying things without knowing, or at least having an idea, of its intended use. But I will try it if I can't get in touch with someone who understands the plugin.

**Comment by illumineawake** [comment]
Yes, that's correct.
