### ISSUE TITLE
Does not loot [ipowerfighter]

### ISSUE THREAD

**Issue by nabulfaz** [illumineawake/illu-plugins#75]
Hi, since yesterday I have experienced an issue with the ipowerfighter, as it does not loot or alch the items specified or based on GE value.

**Comment by SRLJustin** [comment]
Should be fixed in #74

**Comment by nabulfaz** [comment]
Has it been pushed yet? I'm also experiencing issues with Abyssal Demons in Catacombs, it attacks once or twice then runs far away, i.e. the steel dragons and dies.

**Comment by illumineawake** [comment]
It is pushed in 3.4.4
