### ISSUE TITLE
NMZ

### ISSUE THREAD

**Issue by Gittyhub123** [illumineawake/illu-plugins#76]
Again, not a question as such, apologies if this is not ok but I can't find any other support channels.

Is it possible to use this plugin for 6 hour AFK nmz, or are there any other plugins you know about for this? All I need is to stay 1hp and drink absorb pots, potentially overloads as well, and stay 1hp. But most importantly, log out if I leave NMZ.

**Comment by illumineawake** [comment]
Hey mate,
My support server is in the readme/support button in my plugins:
https://discord.com/invite/9fGzEDR
